[package]
name = "cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-mutex = "1.4"
futures = "0.3"
time = "0.3"
tracing = "0.1.36"

[dev-dependencies]
futures-test = "0.3"
